name: CI

on:
  pull_request:
    branches: ["*"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["*"]
    paths-ignore: ["docs/**"]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: set up python
        uses: action/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0